"use client";

import Image from "next/image";
import Link from "next/link";
import { useCustomer } from "@/context/CustomerContext";

export default function OrderDetail({ orderId }: { orderId: string }) {
  const { orders } = useCustomer();
  const order = orders.find((item) => item.id === orderId);
  if (!order) return <div className="rounded-2xl border border-border bg-white p-10 text-center"><h1 className="text-3xl font-semibold">Order not found</h1><p className="mt-3 text-foreground-secondary">This page does not grant download access. Only a confirmed payment creates an order.</p><Link href="/account/orders" className="mt-5 inline-block font-semibold text-primary">Return to My Orders</Link></div>;
  return <><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-primary">Transaction history</p><h1 className="mt-2 text-4xl font-semibold">Order #{order.id}</h1><p className="mt-2 text-foreground-secondary">{new Date(order.createdAt).toLocaleDateString("en-US", { dateStyle: "long" })}</p></div><span className="rounded-full bg-success-soft px-4 py-2 font-semibold text-success">{order.status}</span></div><section className="mt-8 rounded-2xl border border-border bg-white p-6"><h2 className="text-xl font-semibold">Purchased designs</h2><div className="mt-3 divide-y divide-border">{order.items.map((item) => <div key={item.id} className="flex items-center gap-4 py-4"><div className="relative h-16 w-16 shrink-0 overflow-hidden rounded-xl bg-background"><Image src={item.image} alt="" fill className="object-contain" /></div><div className="min-w-0 flex-1"><h3 className="font-semibold">{item.name}</h3><p className="text-sm text-foreground-secondary">{item.hoopSize || "All sizes"} · {item.license || "Personal license"}</p></div><b>${(item.price * item.quantity).toFixed(2)}</b></div>)}</div></section><div className="mt-6 grid gap-6 md:grid-cols-2"><section className="rounded-2xl border border-border bg-white p-6"><h2 className="font-semibold">Payment</h2><p className="mt-3 text-foreground-secondary">{order.paymentReference}</p><p className="mt-1 text-sm text-success">Payment confirmed</p><p className="mt-4 text-sm text-foreground-secondary">Receipt sent to {order.email}</p></section><section className="rounded-2xl border border-border bg-white p-6"><h2 className="font-semibold">Summary</h2><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>${order.subtotal.toFixed(2)}</dd></div><div className="flex justify-between"><dt>Discount</dt><dd>−${order.discount.toFixed(2)}</dd></div><div className="flex justify-between"><dt>Tax</dt><dd>${order.tax.toFixed(2)}</dd></div><div className="flex justify-between border-t border-border pt-2 text-base font-semibold"><dt>Total</dt><dd>${order.total.toFixed(2)}</dd></div></dl></section></div>{order.status === "Completed" && <Link href="/account/downloads" className="mt-7 inline-block rounded-full bg-primary px-5 py-3 font-semibold text-white hover:bg-primary-hover">Access purchased downloads</Link>}</>;
}
