import Link from "next/link";
import { Check, Download, FileText } from "lucide-react";
import type { Product } from "@/types/product";

export default function ProductDetailSections({ product }: { product: Product }) {
  const sizes = product.sizes ?? [{ width: product.width, height: product.height, unit: "mm" as const, stitches: product.stitchCount }];
  const included = product.includedFiles ?? ["Embroidery design files", "Included machine formats", "License information"];
  return <div className="space-y-16 py-14">
    <section><p className="text-sm font-semibold uppercase tracking-wider text-primary">About this design</p><h2 className="mt-2 text-3xl font-semibold">Description</h2><p className="mt-5 max-w-4xl whitespace-pre-line text-lg leading-8 text-foreground-secondary">{product.description}</p>{product.tags?.length ? <div className="mt-6"><h3 className="font-semibold">Tags</h3><div className="mt-3 flex flex-wrap gap-2">{product.tags.map((tag) => <Link key={tag} href={`/search?q=${encodeURIComponent(tag)}`} className="rounded-full bg-secondary px-3 py-1.5 text-sm hover:text-primary">{tag}</Link>)}</div></div> : null}</section>
    <section className="rounded-3xl bg-secondary p-6 sm:p-8"><h2 className="text-3xl font-semibold">Design specifications</h2><dl className="mt-7 grid gap-x-8 gap-y-6 sm:grid-cols-2 lg:grid-cols-3">{[["Colors", String(product.colors ?? product.colorCount)], ["Color changes", String(product.colorChanges ?? product.colorCount)], ["Available sizes", String(sizes.length)], ["Difficulty", product.difficulty], ["Recommended fabric", product.recommendedFabric ?? product.fabric], ["Recommended stabilizer", product.recommendedStabilizer ?? product.stabilizer], ["Thread", product.recommendedThread ?? "40 wt machine embroidery thread"], ["SKU", product.sku ?? `SAM-${product.id}`]].map(([label, value]) => <div key={label}><dt className="text-sm text-foreground-secondary">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl></section>
    <section><h2 className="text-3xl font-semibold">Available sizes</h2><p className="mt-2 text-foreground-secondary">All listed sizes are included with this design.</p><div className="mt-5 overflow-x-auto rounded-2xl border border-border bg-white"><table className="w-full min-w-[420px] text-left"><thead className="bg-secondary text-sm"><tr><th className="px-5 py-3">Size</th><th className="px-5 py-3">Stitches</th></tr></thead><tbody className="divide-y divide-border">{sizes.map((size) => <tr key={`${size.width}-${size.height}`}><td className="px-5 py-3">{size.width} × {size.height} {size.unit}</td><td className="px-5 py-3">{size.stitches.toLocaleString()}</td></tr>)}</tbody></table></div></section>
    <section><h2 className="text-3xl font-semibold">Formats & machine compatibility</h2><h3 className="mt-6 font-semibold">Available formats</h3><div className="mt-3 flex flex-wrap gap-2">{product.formats.map((format) => <span key={format} className="rounded-lg border border-border bg-white px-3 py-2 text-sm font-semibold">{format}</span>)}</div>{product.machineCompatibility?.length ? <><h3 className="mt-8 font-semibold">Machine compatibility</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{product.machineCompatibility.map((machine) => <div key={machine.brand} className="rounded-2xl bg-white p-4"><p className="font-semibold">{machine.brand}</p><p className="mt-1 text-sm text-foreground-secondary">{machine.formats.join(", ")}</p></div>)}</div></> : null}<p className="mt-5 text-sm text-foreground-secondary">Please confirm that your embroidery machine supports one of the included file formats before purchasing.</p></section>
    <section className="grid gap-8 lg:grid-cols-2"><div className="rounded-3xl bg-primary-soft p-6 sm:p-8"><FileText className="h-6 w-6 text-primary" /><h2 className="mt-4 text-2xl font-semibold">Thread color chart</h2><p className="mt-2 text-foreground-secondary">{product.colors ?? product.colorCount} thread colors used in this design.</p><div className="mt-5 flex flex-wrap gap-3"><button type="button" className="rounded-full border border-primary bg-white px-4 py-2 font-semibold text-primary">View color chart</button><button type="button" disabled={!product.colorChart?.pdfUrl} title={!product.colorChart?.pdfUrl ? "PDF preview is not available in this mock project" : undefined} className="flex items-center gap-2 rounded-full bg-primary px-4 py-2 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-45"><Download className="h-4 w-4" /> Download PDF</button></div></div><div><h2 className="text-2xl font-semibold">What’s included</h2><ul className="mt-5 space-y-3">{included.map((item) => <li key={item} className="flex gap-3"><Check className="mt-0.5 h-5 w-5 shrink-0 text-success" />{item}</li>)}</ul><p className="mt-5 font-semibold">Files are provided digitally. Nothing will be shipped.</p></div></section>
    <section className="grid gap-10 border-y border-border py-10 lg:grid-cols-2"><div><h2 className="text-2xl font-semibold">License & usage</h2><p className="mt-4 text-foreground-secondary">Personal, Small Business, and Commercial options are available above. License terms vary by product. Please review the applicable license terms before using the design commercially.</p></div><div><h2 className="text-2xl font-semibold">Digital download</h2><ol className="mt-4 list-decimal space-y-2 pl-5 text-foreground-secondary"><li>Add the design to your cart.</li><li>Complete secure checkout.</li><li>After payment confirmation, find it in My Downloads.</li><li>Download the available embroidery formats.</li><li>Re-download later where permitted.</li></ol><p className="mt-5 font-semibold text-primary">This is a digital machine embroidery file, not a physical embroidered product.</p></div></section>
    <section><h2 className="text-3xl font-semibold">Customer reviews</h2><div className="mt-5 grid gap-6 lg:grid-cols-[260px_1fr]"><div className="rounded-2xl bg-accent-soft p-6"><p className="text-2xl text-accent-hover">★★★★★</p><p className="mt-2 text-3xl font-semibold">{product.rating.toFixed(1)} out of 5</p><p className="mt-1 text-foreground-secondary">{product.reviewCount} reviews</p></div><article className="rounded-2xl bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-foreground-secondary">Mock review for development</p><h3 className="mt-2 text-lg font-semibold">Beautiful stitch-out</h3><p className="mt-2 text-foreground-secondary">The design stitched cleanly and the included sizes were very useful.</p><p className="mt-4 text-sm">Emily R. · August 12, 2026</p></article></div></section>
  </div>;
}
